#' Plot data from spiroergometry files
#'
#' \code{spiro_plot_*()} returns a \code{ggplot2} graph visualising
#' data from a spiroergometric test.
#'
#' This function provides a shortcut for visualising spiroergometric data from
#' \code{\link{spiro}} with \code{ggplot2}. It generates a graph showing the
#' (smoothed) interpolated data, as well as the underlying test protocol.
#'
#' @param data A \code{data.frame} of the class \code{spiro_*}, as it is
#'   generated by \code{\link{spiro}}.
#' @param smooth Integer for calculation of a rolling average (in seconds)
#'   for gas exchange measures.
#'
#' @examples
#' # Import and process example data
#' ramp_data <- spiro(file = spiro_example("zan_ramp"),
#'                   hr_file = spiro_example("hr_ramp.tcx"))
#'
#' spiro_plot_VO2(ramp_data)
#'
#' spiro_plot_HR(ramp_data)
#'
#' @name spiro_plot
NULL

#' @rdname spiro_plot
#' @export
spiro_plot_VO2 <- function(data, smooth = 15) {

  yl <- spiro_plot.guess_units(data)

  ggplot2::ggplot(data = data, ggplot2::aes(x = data$time, y = data$VO2_rel)) +
    ggplot2::geom_area(
      ggplot2::aes(y = load * yl[[1]]),
      colour = "black", alpha = 0.5) +
    list(
      if (!requireNamespace("ggborderline",quietly = TRUE)) {
        ggplot2::geom_line(
          ggplot2::aes(y = zoo::rollmean(data$VCO2_rel, smooth, na.pad = TRUE)),
          colour = "#C00000", size = 1, na.rm = TRUE)
      } else {
        ggborderline::geom_borderline(
          ggplot2::aes(y = zoo::rollmean(data$VCO2_rel, smooth, na.pad = TRUE)),
          colour = "#C00000", size = 1, na.rm = TRUE)
      },
      if (!requireNamespace("ggborderline",quietly = TRUE)) {
        ggplot2::geom_line(
          ggplot2::aes(y = zoo::rollmean(data$VO2_rel, smooth, na.pad = TRUE)),
          colour = "#0053a4", size = 1, na.rm = TRUE)
      } else {
        ggborderline::geom_borderline(
          ggplot2::aes(y = zoo::rollmean(data$VO2_rel, smooth, na.pad = TRUE)),
          colour = "#0053a4", size = 1, na.rm = TRUE)
      }
    ) +
    ggplot2::scale_y_continuous(
      sec.axis = ggplot2::sec_axis( ~. / yl[[1]],
      name = yl[[2]])) +
    ggplot2::labs(x = "Duration [s]", y = "VO2; VCO2 [ml/min/kg]") +
    ggplot2::theme_minimal() +
    ggplot2::theme(panel.grid.minor.x = ggplot2::element_blank())

}

#' @rdname spiro_plot
#' @export

spiro_plot_HR <- function(data) {

  if (all(data$HR == 0, na.rm = TRUE))
    stop("No heart rate data available")
  yl <- spiro_plot.guess_units(data)

  ggplot2::ggplot(data = data, ggplot2::aes(x = data$time, y = data$HR)) +
    ggplot2::geom_point(colour = "red", size = 0.5) +
    ggplot2::geom_area(
      ggplot2::aes(y = load * 3 * yl[[1]]), colour = "black", alpha = 0.5) +
    ggplot2::scale_y_continuous(
      sec.axis = ggplot2::sec_axis( ~. / (3 * yl[[1]]), name = yl[[2]])) +
    ggplot2::labs(x = "Duration [s]", y = "HR [1/min]") +
    ggplot2::theme_minimal() +
    ggplot2::theme(panel.grid.minor.x = ggplot2::element_blank())
}

#' Adjust axes in spiroergometric data plot
#'
#' Internal function to \code{?link{spiro_plot}}
#'
#' @param data A \code{data.frame} of the class \code{spiro_*}.
#' @noRd
spiro_plot.guess_units <- function(data) {
  ymax <- max(data$load, na.rm = TRUE)
  if (ymax <= 8) {
    yscale <- 5
    ylabel <- "Velocity [m/s]"
  } else if (ymax <= 30) {
    yscale <- 2
    ylabel <- "Velocity [km/h]"
  } else {
    yscale <- 0.1
    ylabel <- "Power [W]"
  }
  out <- list(yscale, ylabel)
  out
}
