#' Plot data from spiroergometry files
#'
#' \code{spiro_plot_*} returns a \code{ggplot2} graph visualising
#' data from a spiroergometric test.
#'
#' This function provides a shortcut for visualising spiroergometric data from
#' \code{spiro} with \code{ggplot2}. It generates a graph showing the (smoothed)
#' interpolated data, as well as the underlying test protocol.
#'
#' @param data A \code{data.frame} of the class \code{spiro_*}, as it is
#'   generated by \code{spiro()}.
#' @param smooth Integer for calculation of a rolling average (in seconds)
#'   for gas exchange measures.
#' @param title Logical, whether there should be an automatically generated
#'   title containing participant's name and type of test.
#'
#' @name spiro_plot
NULL

#' @rdname spiro_plot
#' @export
spiro_plot_VO2 <- function(data, smooth = 15, title = FALSE) {

  if (title) {
    t <- spiro_plot.title(data = data)
    } else {
    t <- NULL
    }

  ggplot2::ggplot(data = data, ggplot2::aes(x = data$time, y = data$VO2_rel)) +
    ggplot2::geom_line(colour = "blue") +
    ggplot2::geom_area(ggplot2::aes(y = load * 5),
                       colour = "black", alpha = 0.5) +
    ggplot2::geom_line(ggplot2::aes(y = zoo::rollmean(data$VO2_rel,smooth, na.pad = TRUE)),
                       colour = "red") +
    ggplot2::scale_y_continuous(sec.axis = ggplot2::sec_axis( ~. / 5, name = "Velocity [m/s]")) +
    ggplot2::labs(title = t, x = "Duration [s]", y = "VO2 [ml/min/kg]") +
    ggplot2:: theme_bw()
}

#' @rdname spiro_plot
#' @export

spiro_plot_HR <- function(data, title = FALSE) {

  if (all(data$HR == 0, na.rm = TRUE)) stop("No heart rate data available")
  if (title) {
    t <- spiro_plot.title(data = data)
  } else {
    t <- NULL
  }

  ggplot2::ggplot(data = data, ggplot2::aes(x = data$time, y = data$HR)) +
    ggplot2::geom_point(colour = "red", size = 0.5) +
    ggplot2::geom_area(ggplot2::aes(y = load * 20),
                       colour = "black",
                       alpha = 0.5) +
    ggplot2::scale_y_continuous(
      sec.axis = ggplot2::sec_axis( ~. / 20, name = "Velocity [m/s]")) +
    ggplot2::labs(title = t, x = "Duration [s]", y = "HR [1/min]") +
    ggplot2::theme_bw()
}

spiro_plot.title <- function(data) {
  testtype <- attr(data,"protocol")$testtype
  type <- switch(testtype,
                 constant = "Constant Load Test",
                 ramp = "Ramp Test",
                 increment = "Graded Exercise Test")
  name <- attr(data,"info")$name
  surname <- attr(data,"info")$surname
  title <- paste(type, name, surname)
}
