#' Plot data from cardiopulmonary exercise data files
#'
#' \code{spiro_plot()} returns a \code{ggplot2} graph visualizing
#' data from cardiopulmonary exercise testing.
#'
#' This function provides a shortcut for visualizing spiroergometric data from
#' \code{\link{spiro}} with the help of \code{ggplot2}.
#'
#' @param data A \code{data.frame} of the class \code{spiro}, as it is
#'   generated by \code{\link{spiro}}.
#' @param which A numeric integer setting the plot panels to be displayed. The
#'   panels are numbered in the order of the traditional Wasserman 9-Panel
#'   Plot:
#' * 1: VE over time
#' * 2: HR and oxygen pulse over time
#' * 3: VO2, VCO2 and load over time
#' * 4: VE over VCO2
#' * 5: V-Slope: HR and VCO2 over VO2
#' * 6: EQVO2 and EQVCO2 over time
#' * 7: VT over VE
#' * 8: RER over time
#' * 9: PetO2 and PetCO2 over time
#' @param smooth Parameter giving the filter methods for smoothing the data.
#'   Default is \code{fz} for a zero lag Butterworth filter. See
#'   \code{\link{spiro_smooth}} for more details and other filter methods (e.g.
#'   time based averages),
#' @param base_size An integer controlling the base size of the plots (in pts).
#' @param ... Arguments passed to ggplot2::theme() to modify the appearance of
#'   the plots.
#'
#' @return A ggplot object.
#'
#' @examples
#' # Import and process example data
#' ramp_data <- spiro(
#'   file = spiro_example("zan_ramp"),
#'   hr_file = spiro_example("hr_ramp.tcx")
#' )
#'
#' # Diplay the traditional Wasserman 9-Panel Plot
#' spiro_plot(ramp_data)
#'
#' # Display selected panels, here V-Slope
#' spiro_plot(ramp_data, which = 5)
#' @export

spiro_plot <- function(data, which = 1:9, smooth = "fz", base_size = 13, ...) {

  # input validation for `which` argument
  if (!is.numeric(which) || !all(which %in% 1:9)) {
    stop("'which' must be a numeric vector containing integers between 1 and 9")
  }

  l <- lapply(which, spiro_plot.internal,
    data = data,
    smooth = smooth,
    base_size = base_size,
    ...
  )
  cowplot::plot_grid(plotlist = l)
}

spiro_plot.internal <- function(which, data, smooth, base_size = 15, ...) {
  p <- switch(which,
    `1` = spiro_plot_VE(data, smooth, base_size = base_size, ...),
    `2` = spiro_plot_HR(data, smooth, base_size = base_size, ...),
    `3` = spiro_plot_VO2(data, smooth, base_size = base_size, ...),
    `4` = spiro_plot_EQCO2(data, base_size = base_size, ...),
    `5` = spiro_plot_vslope(data, base_size = base_size, ...),
    `6` = spiro_plot_EQ(data, smooth, base_size = base_size, ...),
    `7` = spiro_plot_vent(data, base_size = base_size, ...),
    `8` = spiro_plot_RER(data, smooth, base_size = base_size, ...),
    `9` = spiro_plot_Pet(data, smooth, base_size = base_size, ...)
  )
  p
}


#' Plot ventilation over time
#'
#' @noRd
spiro_plot_VE <- function(data, smooth = "fz", base_size = 13, ...) {
  d <- spiro_smooth(data["VE"], smooth = smooth, rawsource = data)
  # use raw breath time data if smoothing method is breath-based
  if (attr(d, "smooth_method")$type == "breath") {
    d$t <- attr(data, "raw")$time
  } else {
    d$t <- data$time
  }

  ggplot2::ggplot(
    data = d,
    ggplot2::aes(x = d$t, y = d$VE, colour = "VE (l/min)")
  ) +
    list(
      if (!requireNamespace("ggborderline", quietly = TRUE)) {
        ggplot2::geom_line(
          size = 1, na.rm = TRUE
        )
      } else {
        ggborderline::geom_borderline(
          size = 1, na.rm = TRUE
        )
      }
    ) +
    ggplot2::scale_colour_manual(values = "#003300") +
    ggplot2::labs(x = "Duration (s)", y = NULL) +
    theme_spiro(base_size, ...)
}
#' Plot heartrate and oxygen pulse over time
#'
#' @noRd
spiro_plot_HR <- function(data, smooth = "fz", base_size = 13, ...) {
  sec_factor <- 5

  # Rewrite null values from heart rate to NAs
  data$HR[which(data$HR == 0)] <- NA

  if (!all(is.na(data$HR))) {
    d <- spiro_smooth(data[c("VO2","HR")], smooth = smooth, rawsource = data)
    # use raw breath time data if smoothing method is breath-based
    if (attr(d, "smooth_method")$type == "breath") {
      d$t <- attr(data, "raw")$time
    } else {
      d$t <- data$time
    }

    # if a breath average is chosen but the raw breath data does not contain
    # HR data this will yield only NAs. In this case the time-based average
    # will be calculated displaying a message.
    if (all(is.na(d$HR))) {
      hr <- spiro_smooth(
        data = data["HR"],
        smooth = attr(d, "smooth_method")$param,
        rawsource = data
      )
      # scale heart rate data to
      d$HR <- stats::approx(seq_along(hr$HR), hr$HR, xout = d$t)$y
      message(
        paste0(
          "For heart rate values, time-based smoothing was used instead of",
          " breath-based."
        )
      )
    }
  } else {
    d <- data.frame(
      t = data$time,
      VO2 = data$VO2,
      HR = NA
    )
  }

  d$pulse <- sec_factor * d$VO2 / d$HR

  d_long <- stats::reshape(d,
    direction = "long",
    varying = c("pulse", "HR"),
    v.names = "value",
    idvar = c("t"),
    times = c("pulse", "HR"),
    timevar = "measure"
  )
  d_long$measure <- factor(d_long$measure,
    levels = c("HR", "pulse"),
    labels = c("HR (bpm)", "VO2/HR (ml)")
  )

  ggplot2::ggplot(data = d_long, ggplot2::aes(x = d_long$t)) +
    list(
      if (!requireNamespace("ggborderline", quietly = TRUE)) {
        ggplot2::geom_line(
          ggplot2::aes(y = d_long$value, colour = d_long$measure),
          size = 1, na.rm = TRUE
        )
      } else {
        ggborderline::geom_borderline(
          ggplot2::aes(y = d_long$value, colour = d_long$measure),
          size = 1, na.rm = TRUE
        )
      }
    ) +
    ggplot2::scale_colour_manual(values = c("red", "pink")) +
    list(
      # create a second y-axis only if data values are available as ggplot2
      # returns an error if sec_axis() is applied to all NAs
      if (!all(is.na(d_long$value))) {
        ggplot2::scale_y_continuous(
          limits = c(0, 225),
          sec.axis = ggplot2::sec_axis(~ . / sec_factor)
        )
      } else {
        ggplot2::scale_y_continuous(
          limits = c(0, 225)
        )
      }
    ) +
    ggplot2::labs(x = "Duration (s)", y = NULL) +
    theme_spiro(base_size, ...)
}

#' Plot oxygen uptake, carbon dioxide output and load over time
#'
#' @noRd
spiro_plot_VO2 <- function(data, smooth = "fz", base_size = 13, ...) {
  yl <- spiro_plot.guess_units(data)

  # create data frame with rolling averages
  v_smooth <- spiro_smooth(data[c("VO2", "VCO2")], smooth, data)
  weight <- attr(data, "info")$weight

  tl_data <- data.frame(
    time = data$time,
    load = data$load
  )

  # use raw breath time data if smoothing method is breath-based
  if (attr(v_smooth, "smooth_method")$type == "breath") {
    t_data <- attr(data, "raw")$time
  } else {
    t_data <- data$time
  }

  # create data frame with smoothed data
  v_data <- data.frame(
    time = t_data,
    VO2_rel = v_smooth$VO2 / weight,
    VCO2_rel = v_smooth$VCO2 / weight
  )

  # reshape data into long format
  v_data_long <- stats::reshape(v_data,
    direction = "long",
    varying = c("VO2_rel", "VCO2_rel"),
    v.names = "value",
    idvar = c("time"),
    times = c("VO2_rel", "VCO2_rel"),
    timevar = "measure"
  )

  v_data_long$measure <- factor(v_data_long$measure,
    levels = c("VO2_rel", "VCO2_rel"),
    labels = c("VO2 (ml/min/kg)", "VCO2 (ml/min/kg)")
  )

  ggplot2::ggplot(NULL) +
    ggplot2::geom_area(
      data = tl_data,
      ggplot2::aes_(x = tl_data$time, y = tl_data$load * yl[[1]]),
      colour = "black", alpha = 0.5, position = "identity"
    ) +
    list(
      if (!requireNamespace("ggborderline", quietly = TRUE)) {
        ggplot2::geom_line(
          data = v_data_long,
          ggplot2::aes(
            x = v_data_long$time,
            y = v_data_long$value,
            colour = v_data_long$measure
          ),
          size = 1, na.rm = TRUE
        )
      } else {
        ggborderline::geom_borderline(
          data = v_data_long,
          ggplot2::aes(
            x = v_data_long$time,
            y = v_data_long$value,
            colour = v_data_long$measure
          ),
          size = 1, na.rm = TRUE
        )
      }
    ) +
    ggplot2::scale_y_continuous(
      sec.axis = ggplot2::sec_axis(~ . / yl[[1]],
        name = yl[[2]]
      )
    ) +
    ggplot2::scale_color_manual(values = c("#c00000", "#0053a4")) +
    ggplot2::labs(x = "Duration (s)", y = NULL) +
    theme_spiro(base_size, ...)
}

#' Plot VCO2 vs. VE
#'
#' @noRd
spiro_plot_EQCO2 <- function(data, base_size = 13, ...) {
  raw <- attr(data, "raw")
  # bring VCO2 data into desired unit (l/min)
  raw$VCO2 <- raw$VCO2 / 1000

  ggplot2::ggplot(data = raw, ggplot2::aes(x = raw$VCO2, y = raw$VE)) +
    ggplot2::geom_point(
      size = 2.5,
      shape = 21,
      fill = "#0053a4",
      colour = "white",
      na.rm = TRUE
    ) +
    ggplot2::labs(x = "VCO2 (l/min)", y = "VE (l/min)") +
    theme_spiro(base_size, ...)
}

#' Plot V-Slope graph
#'
#' @noRd
spiro_plot_vslope <- function(data, base_size = 13, ...) {
  raw <- attr(data, "raw")
  # remove rows without time stamp
  raw <- raw[!is.na(raw$time), ]

  # match HR to breath-by-breath raw data if no raw heartrate data is available
  if (!(any(raw$HR != 0, na.rm = TRUE))) {
    raw$HR <- data$HR[replace(round(raw$time), round(raw$time) == 0, 1)]
  }
  # bring VO2 data into desired unit (l/min)
  raw$VO2 <- raw$VO2 / 1000
  # scale VCO2 data for being displayed on second y-axis
  raw$VCO2 <- raw$VCO2 / 20
  raw <- raw[, c("time", "HR", "VO2", "VCO2")]

  raw_long <- stats::reshape(raw,
    direction = "long",
    varying = c("HR", "VCO2"),
    v.names = "value",
    idvar = c("time"),
    times = c("HR", "VCO2"),
    timevar = "measure"
  )
  raw_long$measure <- factor(raw_long$measure,
    levels = c("HR", "VCO2"),
    labels = c("HR (bpm)", "VCO2 (l/min)")
  )

  ggplot2::ggplot(
    data = raw_long,
    mapping = ggplot2::aes(
      x = raw_long$VO2,
      y = raw_long$value,
      fill = raw_long$measure
    )
  ) +
    ggplot2::geom_point(
      size = 2.5,
      shape = 21,
      colour = "white",
      na.rm = TRUE
    ) +
    ggplot2::scale_fill_manual(values = c("red", "#0053a4")) +
    ggplot2::scale_y_continuous(sec.axis = ggplot2::sec_axis(~ . / 50)) +
    ggplot2::labs(x = "VO2 (l/min)", y = NULL) +
    theme_spiro(base_size, ...)
}

#' Plot EQVO2 and EQCO2 over time
#'
#' @noRd
spiro_plot_EQ <- function(data, smooth = "fz", base_size = 13, ...) {

  d <- spiro_smooth(
    data[c("VO2","VCO2","VE")],
    smooth = smooth,
    rawsource = data
  )
  d$EQ_O2 <- 1000 * d$VE / d$VO2
  d$EQ_CO2 <- 1000 * d$VE / d$VCO2
  # use raw breath time data if smoothing method is breath-based
  if (attr(d, "smooth_method")$type == "breath") {
    d$t <- attr(data, "raw")$time
  } else {
    d$t <- data$time
  }

  d_long <- stats::reshape(d,
    direction = "long",
    varying = c("EQ_O2", "EQ_CO2"),
    v.names = "value",
    idvar = c("t"),
    times = c("EQ_O2", "EQ_CO2"),
    timevar = "measure"
  )
  d_long$measure <- factor(d_long$measure, levels = c("EQ_O2", "EQ_CO2"))

  ggplot2::ggplot(data = d_long, ggplot2::aes(x = d_long$t)) +
    list(
      if (!requireNamespace("ggborderline", quietly = TRUE)) {
        ggplot2::geom_line(
          ggplot2::aes(y = d_long$value, colour = d_long$measure),
          size = 1, na.rm = TRUE
        )
      } else {
        ggborderline::geom_borderline(
          ggplot2::aes(y = d_long$value, colour = d_long$measure),
          size = 1, na.rm = TRUE
        )
      }
    ) +
    ggplot2::scale_colour_manual(values = c("#c00000", "#0053a4")) +
    ggplot2::labs(x = "Duration (s)", y = NULL) +
    theme_spiro(base_size, ...)
}

#' Plot VE vs. RR
#'
#' @noRd
spiro_plot_vent <- function(data, base_size = 13, ...) {
  raw <- attr(data, "raw")

  ggplot2::ggplot(data = raw, ggplot2::aes(x = raw$VE, y = raw$VT)) +
    ggplot2::geom_point(
      size = 2.5,
      shape = 21,
      fill = "grey30",
      colour = "white",
      na.rm = TRUE
    ) +
    ggplot2::labs(x = "VE (l/min)", y = "VT (l)") +
    theme_spiro(base_size, ...)
}

#' Plot RER over time
#'
#' @noRd
spiro_plot_RER <- function(data, smooth = "fz", base_size = 13, ...) {
  d <- spiro_smooth(data[c("VO2","VCO2")], smooth = smooth, rawsource = data)
  d$RER <- d$VCO2 / d$VO2
  # use raw breath time data if smoothing method is breath-based
  if (attr(d, "smooth_method")$type == "breath") {
    d$t <- attr(data, "raw")$time
  } else {
    d$t <- data$time
  }

  ggplot2::ggplot(data = d, ggplot2::aes(x = d$t)) +
    list(
      if (!requireNamespace("ggborderline", quietly = TRUE)) {
        ggplot2::geom_line(
          ggplot2::aes(y = d$RER, colour = "RER"),
          size = 1, na.rm = TRUE
        )
      } else {
        ggborderline::geom_borderline(
          ggplot2::aes(y = d$RER, colour = "RER"),
          size = 1, na.rm = TRUE
        )
      }
    ) +
    ggplot2::scale_colour_manual(values = "#003300") +
    ggplot2::labs(x = "Duration (s)", y = NULL) +
    theme_spiro(base_size, ...)
}

#' Plot PetO2 and PetCO2 over time
#'
#' @noRd
spiro_plot_Pet <- function(data, smooth = "fz", base_size = 13, ...) {

  if (!all(is.na(data$PetO2))) {
    d <- spiro_smooth(
      data[c("PetO2","PetCO2")],
      smooth = smooth,
      rawsource = data
    )
    # use raw breath time data if smoothing method is breath-based
    if (attr(d, "smooth_method")$type == "breath") {
      d$t <- attr(data, "raw")$time
    } else {
      d$t <- data$time
    }
  } else {
    d <- data.frame(
      t = data$time,
      # returns error if NAs are interpreted as logical
      PetO2 = as.numeric(NA),
      PetCO2 = as.numeric(NA)
    )
  }

  d_long <- stats::reshape(d,
    direction = "long",
    varying = c("PetO2", "PetCO2"),
    v.names = "value",
    idvar = c("t"),
    times = c("PetO2", "PetCO2"),
    timevar = "measure"
  )
  d_long$measure <- factor(d_long$measure,
    levels = c("PetO2", "PetCO2"),
    labels = c("PetO2 (mmHG)", "PetCO2 (mmHg)")
  )

  ggplot2::ggplot(data = d_long, ggplot2::aes(x = d_long$t)) +
    list(
      if (!requireNamespace("ggborderline", quietly = TRUE)) {
        ggplot2::geom_line(
          ggplot2::aes(y = d_long$value, colour = d_long$measure),
          size = 1, na.rm = TRUE
        )
      } else {
        ggborderline::geom_borderline(
          ggplot2::aes(y = d_long$value, colour = d_long$measure),
          size = 1, na.rm = TRUE
        )
      }
    ) +
    ggplot2::scale_colour_manual(values = c("#c00000", "#0053a4")) +
    ggplot2::scale_y_continuous(limits = c(0, 150)) +
    ggplot2::labs(x = "Duration (s)", y = NULL) +
    theme_spiro(base_size, ...)
}

#' Adjust axes in spiroergometric data plot
#'
#' Internal function to \code{?link{spiro_plot}}
#'
#' @param data A \code{data.frame} of the class \code{spiro_*}.
#' @noRd
spiro_plot.guess_units <- function(data) {
  ymax <- max(data$load, na.rm = TRUE)
  if (ymax <= 8) {
    yscale <- 5
    ylabel <- "Velocity (m/s)"
  } else if (ymax <= 30) {
    yscale <- 2
    ylabel <- "Velocity (km/h)"
  } else {
    yscale <- 0.1
    ylabel <- "Power (W)"
  }
  out <- list(yscale, ylabel)
  out
}

#' Internal ggplot2 theme for spiro plots
#'
#'
#' @param base_size An integer, giving the base size for the theme.
#' @param ... Arguments passed to ggplot2::theme()
#'
#' @noRd
theme_spiro <- function(base_size = 13,
                        panel.grid.minor.x = ggplot2::element_blank(),
                        legend.position = c(0.02, 0.98),
                        legend.background = ggplot2::element_rect(
                          colour = NA,
                          fill = ggplot2::alpha("white", 0.9)
                        ),
                        legend.justification = c(0, 1),
                        legend.title = ggplot2::element_blank(),
                        ...) {
  list(
    ggplot2::theme_minimal(base_size = base_size),
    ggplot2::theme(
      panel.grid.minor.x = panel.grid.minor.x,
      legend.position = legend.position,
      legend.background = legend.background,
      legend.justification = legend.justification,
      legend.title = legend.title,
      ...
    )
  )
}
