#' Return maximum values from spiroergometric tests
#'
#' \code{spiro_max()} returns a \code{data.frame} with the maximum parameter
#' parameters of a spiroergometric test.
#'
#' Before calculating the maximum values, data is smoothed by using a rolling
#' average over the length of \code{interval}.
#'
#' @param data A \code{data.frame} of the class \code{spiro}, as it is
#'   generated by \code{\link{spiro}}.
#' @param smooth An integer, giving the length of the computational
#'   interval for the rolling average.
#' @param hr_smooth A logical, whether smoothing should also apply to heart rate
#'   data. Default is `FALSE`, which means that the absolute maximum heart rate
#'   value is taken without smoothing.
#'
#' @examples
#' # Import and process example data sets
#' gxt_data <- spiro(file = spiro_example("zan_gxt"))
#'
#' spiro_max(gxt_data)
#' @export

spiro_max <- function(data, smooth = 30, hr_smooth = FALSE) {

  # input validation for `smooth` argument
  if (!is.numeric(smooth)) {
    stop("'smooth' must be an integer")
  } else if (smooth < 1) {
    stop("'smooth' must be greater or equal to 1")
  }

  if (!is.logical(hr_smooth)) {
    stop("'hr_smooth' must be either TRUE or FALSE")
  }

  # calculate rolling averages
  data$VO2_rm <- zoo::rollmean(data$VO2, smooth, fill = NA)
  data$VCO2_rm <- zoo::rollmean(data$VCO2, smooth, fill = NA)
  data$VO2_rel_rm <- zoo::rollmean(data$VO2_rel, smooth, fill = NA)
  data$VE_rm <- zoo::rollmean(data$VE, smooth, fill = NA)
  data$RER_rm <- zoo::rollmean(data$RER, smooth, fill = NA)

  # Use only data during exercising for calculating maximum values
  # Does not apply to HR, since this can also be achieved shortly after
  # termination
  if (any(data$step != 0)) {
    data_cut <- data[data$step >= 1, ]
  } else {
    data_cut <- data
  }

  df <- data.frame(
    VO2 = max(data_cut$VO2_rm, na.rm = TRUE),
    VCO2 = max(data_cut$VCO2_rm, na.rm = TRUE),
    VO2_rel = max(data_cut$VO2_rel_rm, na.rm = TRUE),
    VE = max(data_cut$VE_rm, na.rm = TRUE),
    RER = max(data_cut$RER_rm, na.rm = TRUE)
  )
  df <- round(df, 2) # round data to two decimals

  # check if HR data is available
  if (!all(is.na(data$HR))) {
    if (hr_smooth) {
      # apply smoothing to heart rate data
      hr_max <- round(
        max(zoo::rollmean(data$HR, smooth, fill = NA),
            na.rm = TRUE
        )
      )
    } else {
      hr_max <- max(data$HR, na.rm = TRUE)
    }
    df_hr <- data.frame(HR = hr_max)
  } else {
    df_hr <- data.frame(HR = NA)
  }

  df <- cbind(df, df_hr)

  # write calculation interval as attribute (useful for reactive environments)
  attr(df, "interval") <- smooth

  df
}
