#' Stepwise summarise data from spiroergometric tests
#'
#' \code{spiro_summary()} returns a \code{data.frame} summarising the main
#' parameters for each step of a spiroergometric test.
#'
#' This function generates mean values of gas exchange and cardiac parameters
#' for all steps of a spiroergometric test. For calculation the given
#' \code{interval} before the end of each step is used.
#'
#' @param data A \code{data.frame} of the class \code{spiro_*}, as it is
#'   generated by \code{\link{spiro}}.
#' @param interval An integer giving the length of the computational
#'   interval in seconds.
#'
#' @export

spiro_summary <- function(data, interval = 30) {
  protocol <- attr(data, "protocol")
  if (all(is.na(protocol)))
    stop("No protocol found")

  steplength <- protocol$step.duration
  stepcount <- protocol$step.count
  if (interval > steplength) {
    interval <- steplength
    message("'interval' was set to step length")
  }

  predf <- NULL
  wudf <- NULL
  if (protocol$pre.duration >= interval) {
    predf <- sapply(0, getstepmeans, data = data, interval = interval)
  } else if (protocol$pre.duration > 0) {
    predf <- sapply(0, getstepmeans,
                    data = data,
                    interval = protocol$pre.duration)
    message("for pre-measures, interval was set to length of measures")
  }
  if (protocol$wu.duration >= interval) {
    wudf <- sapply(0.5, getstepmeans, data = data, interval = interval)
  } else if (protocol$wu.duration > 0) {
    predf <- sapply(0, getstepmeans,
                    data = data,
                    interval = protocol$wu.duration)
    message("for warm-up measures, interval was set to length of warm-up")
  }

  steps <- 1:trunc(stepcount)
  ldf <- sapply(steps, getstepmeans, data = data, interval = interval)
  ldf <- cbind(predf, wudf, ldf)
  df <- round(data.frame(apply(t(ldf),2,unlist)),2)
  df
}

#' Overall summarise data from spiroergometric tests
#'
#' \code{spiro_glance()} returns a \code{data.frame} overall summarising the
#' parameters of a spiroergometric test.
#'
#' This function generates a overall summary of gas exchange and cardiac
#' parameters for spiroergometric tests.
#'
#' For constant load tests, the mean parameters for the given load are
#' calculated over all steps. The length of the computational interval before
#' the end of each step is given by \code{interval}.
#'
#' For other test protocols, the maximum parameters are calculated. Data is
#' smoothed before by using a rolling average over the length of
#' \code{interval}.
#'
#' @param data A \code{data.frame} of the class \code{spiro_*}, as it is
#'   generated by \code{\link{spiro}}.
#' @param interval An integer, giving the length of the computational
#'   interval in seconds.
#'
#' @export

spiro_glance <- function(data, interval) {
  UseMethod("spiro_glance")
}


#' @describeIn spiro_glance The default method, which gives maximal values of
#'   the rolling averages.
#' @export

spiro_glance.default <- function(data, interval = 30) {
  data$VO2_rm <- zoo::rollmean(data$VO2, interval, na.pad = TRUE)
  data$VO2_rel_rm <- zoo::rollmean(data$VO2_rel, interval, na.pad = TRUE)
  data$RER_rm <- zoo::rollmean(data$RER, interval, na.pad = TRUE)
  data$HR_rm <- zoo::rollmean(data$HR, interval, na.pad = TRUE)
  if (any(data$step != 0)) data <- data[data$step >= 1,]

  df <- data.frame(
    VO2max_abs = max(data$VO2_rm, na.rm = TRUE),
    VO2max_rel = max(data$VO2_rel_rm, na.rm = TRUE),
    RER_max = max(data$RER_rm, na.rm = TRUE)
  )
  df <- round(df, 2)

  if (!all(data$HR == 0, na.rm = TRUE)) {
    df_hr <- data.frame(HR_max = round(max(data$HR_rm, na.rm = TRUE),0))
    df <- cbind(df, df_hr)
  }
  df
}

#' @describeIn spiro_glance Method for constant load tests, which gives an
#'   average of all steps performed at the constant load.
#' @export
spiro_glance.spiro_clt <- function(data, interval = 30) {
  protocol <- attr(data, "protocol")
  steps <- 1:trunc(protocol$step.count)
  ldf <- sapply(steps, getstepmeans, data = data, interval = interval)
  m <- apply(ldf,2,unlist)
  mm <- round(rowMeans(m),2)[-1]
  df_out <- data.frame(t(mm))
  df_out
}

#' Get mean data values for a step of an exercise test
#'
#' code{getstepmeans()} returns the average data values for a single step pf an
#' exercise test.
#'
#' @param step_number An integer giving the number of the step
#' @param data A \code{data.frame} of the class \code{exed_*} containing the
#'    data of the test
#' @param interval An integer giving the length of the computational interval
#'    in seconds. For calculation the last \code{interval} seconds of the step
#'    will be averaged.
getstepmeans <- function(step_number, data, interval = 30) {
  step <- data[data$step == step_number,]
  stepend <- step[(nrow(step)-(interval-1)):nrow(step),]

  df <- data.frame(
    step_number = step_number,
    load = mean(stepend$load, na.rm = TRUE),
    VE = mean(stepend$VE, na.rm = TRUE),
    VO2 = mean(stepend$VO2, na.rm = TRUE),
    VCO2 = mean(stepend$VCO2, na.rm = TRUE),
    RER = mean(stepend$RER, na.rm = TRUE),
    VO2_rel = mean(stepend$VO2_rel, na.rm = TRUE),
    RE = mean(stepend$RE, na.rm = FALSE)
  )

  if (!all(data$HR == 0, na.rm = TRUE)) {
    df_hr <- data.frame(HR = mean(stepend$HR, na.rm = FALSE))
    df <- cbind(df, df_hr)
  }
  df
}
